language: generic
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="lua=5.4"
  - LUA="luajit=2.0"
  - LUA="luajit https://github.com/luajit/luajit.git@v2.1"

jobs:
  - os: osx
  - os: linux

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks make --only-deps

script:
  - luarocks lint tl-dev*rockspec
  - make selfbuild
  - luarocks test

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
